name: Build and Package Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Specify the Ruby version

      - name: Install Bundler
        run: gem install bundler -v 2.7.2

      - name: Install dependencies
        run: bundle install
        working-directory: src

      - name: Build the site
        run: bundle exec jekyll build
        working-directory: src

      - name: Package the site
        run: zip -r site.zip ./_site
        working-directory: src

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-artifact-${{ github.ref_name }}-${{ github.sha }}
          path: site.zip